install:
  - ps: |
      if ($env:PLATFORM -eq "x86") {
        Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-gnu.exe' -FileName rust.exe
      } else {
        Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-x86_64-pc-windows-gnu.exe' -FileName rust.exe
      }
  - rust.exe /VERYSILENT /NORESTART /DIR="C:\Program Files\Rust"
  - SET PATH=%PATH%;C:\Program Files\Rust\bin;C:\MinGW\bin
  - rustc -V
  - cargo -V

platform:
  - x86

build: false

test_script:
  - cargo test --verbose
